// <auto-generated />
namespace OnlineMovieTicket.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adddatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "202003301341043_add datetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
