// <auto-generated />
namespace OnlineMovieTicket.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class onlineMoviev1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onlineMoviev1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003181713561_onlineMovie-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
